//////////////////////////////////////////////////////////////////////////
// This file is AUTOGENERATED
//
// any changes to this file will be discarded upon rebuild
//
// please edit version numbers in AssemblyVersion.txt
//

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// 
//      Build Number gets placed in strings below using HG version info

[assembly: AssemblyVersion("2.3.643.1")]
[assembly: AssemblyFileVersion("2.3.643.1")]

