@echo copying test images for SilverlightTestApplication
@echo off
set TARGET_DIR="..\SilverlightTest\SilverlightTestApplication.Web\ClientBin\TestTiffs\"
cd ..\TestCase
copy /Y "bitmap-zip-pc.tif" %TARGET_DIR%
copy /Y "cas.tif" %TARGET_DIR%
copy /Y "CCITT_1.TIF" %TARGET_DIR%
copy /Y "CCITT_2.TIF" %TARGET_DIR%
copy /Y "CCITT_3.TIF" %TARGET_DIR%
copy /Y "CCITT_4.TIF" %TARGET_DIR%
copy /Y "CCITT_5.TIF" %TARGET_DIR%
copy /Y "CCITT_6.TIF" %TARGET_DIR%
copy /Y "CCITT_7.TIF" %TARGET_DIR%
copy /Y "CCITT_8.TIF" %TARGET_DIR%
copy /Y "cmyk8-lzw.tif" %TARGET_DIR%
copy /Y "color64-lzw-mac.tif" %TARGET_DIR%
copy /Y "color64-lzw-pc.tif" %TARGET_DIR%
copy /Y "cramps-tile.tif" %TARGET_DIR%
copy /Y "cramps.tif" %TARGET_DIR%
copy /Y "dscf0013.tif" %TARGET_DIR%
copy /Y "fax2d.tif" %TARGET_DIR%
copy /Y "FLAG_T24.TIF" %TARGET_DIR%
copy /Y "G31D.TIF" %TARGET_DIR%
copy /Y "G31DS.TIF" %TARGET_DIR%
copy /Y "G32D.TIF" %TARGET_DIR%
copy /Y "G32DS.TIF" %TARGET_DIR%
copy /Y "g3test.tif" %TARGET_DIR%
copy /Y "G4.TIF" %TARGET_DIR%
copy /Y "G4S.TIF" %TARGET_DIR%
copy /Y "GMARBLES.TIF" %TARGET_DIR%
copy /Y "gray8-lzw-mac.tif" %TARGET_DIR%
copy /Y "gray8-packbits-be.tif" %TARGET_DIR%
copy /Y "gray8-packbits-le.tif" %TARGET_DIR%
copy /Y "gray8-zip-pc.tif" %TARGET_DIR%
copy /Y "jello.tif" %TARGET_DIR%
copy /Y "jim___ah.tif" %TARGET_DIR%
copy /Y "jim___cg.tif" %TARGET_DIR%
copy /Y "jim___dg.tif" %TARGET_DIR%
copy /Y "jim___gg.tif" %TARGET_DIR%
copy /Y "lab8-lzw.tif" %TARGET_DIR%
copy /Y "MARBIBM.TIF" %TARGET_DIR%
copy /Y "MARBLES.TIF" %TARGET_DIR%
copy /Y "multipage.tif" %TARGET_DIR%
copy /Y "oxford.tif" %TARGET_DIR%
copy /Y "penguin_jpeg.tif" %TARGET_DIR%
copy /Y "pc260001.tif" %TARGET_DIR%
copy /Y "quad-jpeg.tif" %TARGET_DIR%
copy /Y "quad-lzw.tif" %TARGET_DIR%
copy /Y "quad-tile.tif" %TARGET_DIR%
copy /Y "rgb8-jpeg-RGB.tif" %TARGET_DIR%
copy /Y "rgb8-jpeg-YCrCb.tif" %TARGET_DIR%
copy /Y "rgb8-lsb2msb.tif" %TARGET_DIR%
copy /Y "rgb8-lzw-mac.tif" %TARGET_DIR%
copy /Y "rgb8-lzw-pc.tif" %TARGET_DIR%
copy /Y "rgb8-msb2lsb.tif" %TARGET_DIR%
copy /Y "rgb8-separate.tif" %TARGET_DIR%
copy /Y "rgb8-zip-mac.tif" %TARGET_DIR%
copy /Y "rgb8-zip-pc.tif" %TARGET_DIR%
copy /Y "strike.tif" %TARGET_DIR%
copy /Y "tiger-minisblack-strip-01.tif" %TARGET_DIR%
copy /Y "tiger-minisblack-strip-02.tif" %TARGET_DIR%
copy /Y "tiger-minisblack-strip-04.tif" %TARGET_DIR%
copy /Y "tiger-minisblack-strip-08.tif" %TARGET_DIR%
copy /Y "tiger-minisblack-tile-01.tif" %TARGET_DIR%
copy /Y "tiger-minisblack-tile-02.tif" %TARGET_DIR%
copy /Y "tiger-minisblack-tile-04.tif" %TARGET_DIR%
copy /Y "tiger-minisblack-tile-08.tif" %TARGET_DIR%
copy /Y "tiger-palette-strip-01.tif" %TARGET_DIR%
copy /Y "tiger-palette-strip-02.tif" %TARGET_DIR%
copy /Y "tiger-palette-strip-03.tif" %TARGET_DIR%
copy /Y "tiger-palette-strip-04.tif" %TARGET_DIR%
copy /Y "tiger-palette-strip-05.tif" %TARGET_DIR%
copy /Y "tiger-palette-strip-06.tif" %TARGET_DIR%
copy /Y "tiger-palette-strip-07.tif" %TARGET_DIR%
copy /Y "tiger-palette-strip-08.tif" %TARGET_DIR%
copy /Y "tiger-palette-tile-01.tif" %TARGET_DIR%
copy /Y "tiger-palette-tile-02.tif" %TARGET_DIR%
copy /Y "tiger-palette-tile-03.tif" %TARGET_DIR%
copy /Y "tiger-palette-tile-04.tif" %TARGET_DIR%
copy /Y "tiger-palette-tile-05.tif" %TARGET_DIR%
copy /Y "tiger-palette-tile-06.tif" %TARGET_DIR%
copy /Y "tiger-palette-tile-07.tif" %TARGET_DIR%
copy /Y "tiger-palette-tile-08.tif" %TARGET_DIR%
copy /Y "tiger-rgb-strip-contig-01.tif" %TARGET_DIR%
copy /Y "tiger-rgb-strip-contig-02.tif" %TARGET_DIR%
copy /Y "tiger-rgb-strip-contig-04.tif" %TARGET_DIR%
copy /Y "tiger-rgb-strip-contig-08.tif" %TARGET_DIR%
copy /Y "tiger-rgb-strip-planar-08.tif" %TARGET_DIR%
copy /Y "tiger-rgb-tile-contig-01.tif" %TARGET_DIR%
copy /Y "tiger-rgb-tile-contig-02.tif" %TARGET_DIR%
copy /Y "tiger-rgb-tile-contig-04.tif" %TARGET_DIR%
copy /Y "tiger-rgb-tile-contig-08.tif" %TARGET_DIR%
copy /Y "tiger-rgb-tile-planar-08.tif" %TARGET_DIR%
copy /Y "tiger-separated-strip-contig-08.tif" %TARGET_DIR%
copy /Y "tiger-separated-strip-planar-08.tif" %TARGET_DIR%
copy /Y "XING_T24.TIF" %TARGET_DIR%
copy /Y "ycbcr-cat.tif" %TARGET_DIR%