using System;
using System.Collections.Generic;
using System.Text;

namespace BitMiracle.Docotic.PDFLib
{
    enum PdfExceptionType
    {
        UnknownPdfException = 0,
        MemoryAllocationFailed,
        InvalidObject,
        InvalidIndex,
        InvalidDestination,
        InvalidParameter,
        InvalidImage,
        InvalidJpegImage,
        InvalidBMPImage,
        InvalidPngImage,
        InvalidGifImage,
        InvalidTiffImage,
        InvalidXObject,
        InvalidDocument,
        InvalidItem,
        ArrayLengthExceeded,
        DictionaryLengthExceeded,
        XrefLengthExceeded,
        RealValueIsOutOfRange,
        NameIsTooLong,
        BinaryIsTooLong,
        StringIsTooLong,
        GStateStackDepthExceeded,
        ZLibError,
        LibPngError,
        FileOpenFailed,
        FileIOError,
        CannotGetEncryptionDictionary,
        CannotGetDictionaryItem,
        CannotGetPNGPallete,
        CannotSetParent,
        CannotRestoreState,
        CannotShowText,
        JWWCodeLimitExceeded,
        StreamError,
        UnsupportedEncryptAlgorithm,

        IncorrectLexeme,
        WrongDocumentHeader,
        UnsupportedDocumentFormat,
        WrongStartxref,
        WrongTrailer,
        WrongXref,
        WrongDictionary,
        WrongCatalog,
        WrongPages,
        WrongPage,
        WrongFont,
        WrongEncoding,
        WrongResources,
        WrongArray,
        WrongObject,
        WrongString,
        WrongControlName,
        WrongEncryptDictionary,
        WrongPassword,
        InvalidPageOperator,
        UnsupportedFont,
        WrongViewerPreferences,
        AlreadyAttached,
        NotAttached,
        UnsupportedActionType,
        CannotDeleteAlonePage,
        CannotDeleteCurrentPage,
        LZWTableOverflow,
        UnsupportedEncryptor,
        UnsupportedColorSpace,
        WrongBitmap,
        CannotUseColorWithColoredPattern,
        UnsupportedJpegImage,
        UnsupportedBMPImage,
    }
}
